spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-sweet-queen-a1h6dqly.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YWjAizSIH7M9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# JWT Configuration
jwt.secret=your-super-secret-key-that-should-be-at-least-256-bits-long-for-hs256-algorithm-change-me-in-production
jwt.expiration=86400000